// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/base.proto

package pkg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResultadoGuardar struct {
	Clave                string   `protobuf:"bytes,1,opt,name=Clave,proto3" json:"Clave,omitempty"`
	Valor                int32    `protobuf:"varint,2,opt,name=Valor,proto3" json:"Valor,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResultadoGuardar) Reset()         { *m = ResultadoGuardar{} }
func (m *ResultadoGuardar) String() string { return proto.CompactTextString(m) }
func (*ResultadoGuardar) ProtoMessage()    {}
func (*ResultadoGuardar) Descriptor() ([]byte, []int) {
	return fileDescriptor_e927cd757357cbd9, []int{0}
}

func (m *ResultadoGuardar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultadoGuardar.Unmarshal(m, b)
}
func (m *ResultadoGuardar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultadoGuardar.Marshal(b, m, deterministic)
}
func (m *ResultadoGuardar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultadoGuardar.Merge(m, src)
}
func (m *ResultadoGuardar) XXX_Size() int {
	return xxx_messageInfo_ResultadoGuardar.Size(m)
}
func (m *ResultadoGuardar) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultadoGuardar.DiscardUnknown(m)
}

var xxx_messageInfo_ResultadoGuardar proto.InternalMessageInfo

func (m *ResultadoGuardar) GetClave() string {
	if m != nil {
		return m.Clave
	}
	return ""
}

func (m *ResultadoGuardar) GetValor() int32 {
	if m != nil {
		return m.Valor
	}
	return 0
}

func (m *ResultadoGuardar) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ResultadoObtenerEliminar struct {
	Valor                string   `protobuf:"bytes,1,opt,name=Valor,proto3" json:"Valor,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResultadoObtenerEliminar) Reset()         { *m = ResultadoObtenerEliminar{} }
func (m *ResultadoObtenerEliminar) String() string { return proto.CompactTextString(m) }
func (*ResultadoObtenerEliminar) ProtoMessage()    {}
func (*ResultadoObtenerEliminar) Descriptor() ([]byte, []int) {
	return fileDescriptor_e927cd757357cbd9, []int{1}
}

func (m *ResultadoObtenerEliminar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultadoObtenerEliminar.Unmarshal(m, b)
}
func (m *ResultadoObtenerEliminar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultadoObtenerEliminar.Marshal(b, m, deterministic)
}
func (m *ResultadoObtenerEliminar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultadoObtenerEliminar.Merge(m, src)
}
func (m *ResultadoObtenerEliminar) XXX_Size() int {
	return xxx_messageInfo_ResultadoObtenerEliminar.Size(m)
}
func (m *ResultadoObtenerEliminar) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultadoObtenerEliminar.DiscardUnknown(m)
}

var xxx_messageInfo_ResultadoObtenerEliminar proto.InternalMessageInfo

func (m *ResultadoObtenerEliminar) GetValor() string {
	if m != nil {
		return m.Valor
	}
	return ""
}

func (m *ResultadoObtenerEliminar) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ParametroGuardar struct {
	Clave                string   `protobuf:"bytes,1,opt,name=Clave,proto3" json:"Clave,omitempty"`
	Valor                string   `protobuf:"bytes,2,opt,name=Valor,proto3" json:"Valor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParametroGuardar) Reset()         { *m = ParametroGuardar{} }
func (m *ParametroGuardar) String() string { return proto.CompactTextString(m) }
func (*ParametroGuardar) ProtoMessage()    {}
func (*ParametroGuardar) Descriptor() ([]byte, []int) {
	return fileDescriptor_e927cd757357cbd9, []int{2}
}

func (m *ParametroGuardar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParametroGuardar.Unmarshal(m, b)
}
func (m *ParametroGuardar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParametroGuardar.Marshal(b, m, deterministic)
}
func (m *ParametroGuardar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParametroGuardar.Merge(m, src)
}
func (m *ParametroGuardar) XXX_Size() int {
	return xxx_messageInfo_ParametroGuardar.Size(m)
}
func (m *ParametroGuardar) XXX_DiscardUnknown() {
	xxx_messageInfo_ParametroGuardar.DiscardUnknown(m)
}

var xxx_messageInfo_ParametroGuardar proto.InternalMessageInfo

func (m *ParametroGuardar) GetClave() string {
	if m != nil {
		return m.Clave
	}
	return ""
}

func (m *ParametroGuardar) GetValor() string {
	if m != nil {
		return m.Valor
	}
	return ""
}

type ParametroObtenerEliminar struct {
	Clave                string   `protobuf:"bytes,1,opt,name=clave,proto3" json:"clave,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParametroObtenerEliminar) Reset()         { *m = ParametroObtenerEliminar{} }
func (m *ParametroObtenerEliminar) String() string { return proto.CompactTextString(m) }
func (*ParametroObtenerEliminar) ProtoMessage()    {}
func (*ParametroObtenerEliminar) Descriptor() ([]byte, []int) {
	return fileDescriptor_e927cd757357cbd9, []int{3}
}

func (m *ParametroObtenerEliminar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParametroObtenerEliminar.Unmarshal(m, b)
}
func (m *ParametroObtenerEliminar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParametroObtenerEliminar.Marshal(b, m, deterministic)
}
func (m *ParametroObtenerEliminar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParametroObtenerEliminar.Merge(m, src)
}
func (m *ParametroObtenerEliminar) XXX_Size() int {
	return xxx_messageInfo_ParametroObtenerEliminar.Size(m)
}
func (m *ParametroObtenerEliminar) XXX_DiscardUnknown() {
	xxx_messageInfo_ParametroObtenerEliminar.DiscardUnknown(m)
}

var xxx_messageInfo_ParametroObtenerEliminar proto.InternalMessageInfo

func (m *ParametroObtenerEliminar) GetClave() string {
	if m != nil {
		return m.Clave
	}
	return ""
}

func init() {
	proto.RegisterType((*ResultadoGuardar)(nil), "base.ResultadoGuardar")
	proto.RegisterType((*ResultadoObtenerEliminar)(nil), "base.ResultadoObtenerEliminar")
	proto.RegisterType((*ParametroGuardar)(nil), "base.ParametroGuardar")
	proto.RegisterType((*ParametroObtenerEliminar)(nil), "base.ParametroObtenerEliminar")
}

func init() {
	proto.RegisterFile("pkg/base.proto", fileDescriptor_e927cd757357cbd9)
}

var fileDescriptor_e927cd757357cbd9 = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0xc8, 0x4e, 0xd7,
	0x4f, 0x4a, 0x2c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x42,
	0xb8, 0x04, 0x82, 0x52, 0x8b, 0x4b, 0x73, 0x4a, 0x12, 0x53, 0xf2, 0xdd, 0x4b, 0x13, 0x8b, 0x52,
	0x12, 0x8b, 0x84, 0x44, 0xb8, 0x58, 0x9d, 0x73, 0x12, 0xcb, 0x52, 0x25, 0x18, 0x15, 0x18, 0x35,
	0x38, 0x83, 0x20, 0x1c, 0x90, 0x68, 0x58, 0x62, 0x4e, 0x7e, 0x91, 0x04, 0x93, 0x02, 0xa3, 0x06,
	0x6b, 0x10, 0x84, 0x03, 0x12, 0x75, 0x2d, 0x2a, 0xca, 0x2f, 0x92, 0x60, 0x86, 0xa8, 0x05, 0x73,
	0x94, 0xdc, 0xb8, 0x24, 0xe0, 0xa6, 0xfa, 0x27, 0x95, 0xa4, 0xe6, 0xa5, 0x16, 0xb9, 0xe6, 0x64,
	0xe6, 0x66, 0xe6, 0x41, 0x4c, 0x87, 0x98, 0x03, 0x35, 0x1d, 0xcd, 0x1c, 0x26, 0x64, 0x73, 0xec,
	0xb8, 0x04, 0x02, 0x12, 0x8b, 0x12, 0x73, 0x53, 0x4b, 0x8a, 0x48, 0x71, 0x1d, 0xcc, 0x54, 0x25,
	0x03, 0x2e, 0x09, 0xb8, 0x7e, 0x2c, 0xee, 0x48, 0x46, 0x36, 0x07, 0xcc, 0x31, 0xba, 0xc1, 0xc8,
	0xc5, 0xe2, 0x94, 0x58, 0x9c, 0x2a, 0x64, 0xc9, 0xc5, 0x9e, 0x0e, 0xb5, 0x51, 0x4c, 0x0f, 0x1c,
	0x6c, 0xe8, 0x2e, 0x91, 0x82, 0x8a, 0x63, 0x84, 0x9f, 0x27, 0x17, 0x7b, 0x3e, 0xc4, 0x32, 0x21,
	0x39, 0x34, 0xad, 0x68, 0x8e, 0x90, 0x92, 0x43, 0x33, 0x02, 0xdd, 0x91, 0x5e, 0x5c, 0x1c, 0xa9,
	0x30, 0x36, 0x85, 0x66, 0x39, 0x71, 0x45, 0x71, 0x80, 0x14, 0xe8, 0x17, 0x64, 0xa7, 0x27, 0xb1,
	0x81, 0xd3, 0x80, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x86, 0x3a, 0xe7, 0x2e, 0x15, 0x02, 0x00,
	0x00,
}
